"""initial_schema

Revision ID: fdbf5de59fe6
Revises: 
Create Date: 2026-04-20 12:38:40.858992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbf5de59fe6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compilation_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('affected_raw_ids', sa.JSON(), nullable=True),
    sa.Column('affected_wiki_slugs', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure_raw',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titolo', sa.String(length=300), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('contenuto_md', sa.Text(), nullable=False),
    sa.Column('autore', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('compilation_status', sa.String(length=20), nullable=False),
    sa.Column('compilation_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedure_wiki',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('titolo', sa.String(length=300), nullable=False),
    sa.Column('contenuto_md', sa.Text(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('source_raw_ids', sa.JSON(), nullable=True),
    sa.Column('last_compiled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compilation_model', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('wiki_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_md', sa.Text(), nullable=True),
    sa.Column('last_rebuilt_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki_index')
    op.drop_table('procedure_wiki')
    op.drop_table('procedure_raw')
    op.drop_table('compilation_log')
    # ### end Alembic commands ###
